WITH CTE AS (
select 
    __EVENT_DOMAIN,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	ITEMDATAAREAID,
	ITEMGROUPDATAAREAID,
	ITEMGROUPID,
	ITEMID,
	OPERATIONALREPORTINGREFREC,
	PARTITION,
	RECID,
	RECVERSION,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__LOAD_TS,
    ROW_NUMBER() OVER (PARTITION BY RECID ORDER BY __EVENT_TS desc) as RN
    
 FROM {{ ref('src_plax_inventitemgroupitem') }})
 

SELECT 
   __EVENT_DOMAIN,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	ITEMDATAAREAID,
	ITEMGROUPDATAAREAID,
	ITEMGROUPID,
	ITEMID,
	OPERATIONALREPORTINGREFREC,
	PARTITION,
	RECID,
	RECVERSION,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__LOAD_TS
from CTE 
WHERE RN=1 and __SYS_CHANGE_OPERATION<>'D'


