WITH CTE AS (
select 
    DENOMINATOR,
	__EVENT_DOMAIN,
	__EVENT_FIELD_TAGS,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	FACTOR,
	FROMUNITOFMEASURE,
	INNEROFFSET,
	MODIFIEDDATETIME,
	NUMERATOR,
	OUTEROFFSET,
	PARTITION,
	PRODUCT,
	RECID,
	RECVERSION,
	ROUNDING,
	TOUNITOFMEASURE,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__LOAD_TS
    ROW_NUMBER() OVER (PARTITION BY RECID ORDER BY MODIFIEDDATETIME desc) as RN
    
 FROM {{ ref('src_plax_unitofmeasureconversion') }})
 

SELECT 
   DENOMINATOR,
	__EVENT_DOMAIN,
	__EVENT_FIELD_TAGS,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	FACTOR,
	FROMUNITOFMEASURE,
	INNEROFFSET,
	MODIFIEDDATETIME,
	NUMERATOR,
	OUTEROFFSET,
	PARTITION,
	PRODUCT,
	RECID,
	RECVERSION,
	ROUNDING,
	TOUNITOFMEASURE,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__LOAD_TS
from CTE 
WHERE RN=1 and __SYS_CHANGE_OPERATION<>'D'

