WITH CTE AS (
select 
    CGKPRDROUNDDOWN,
	DECIMALPRECISION,
	EXPORTTOESKER,
	MODIFIEDDATETIME,
	PALLETTYPE,
	PARTITION,
	RECID,
	RECVERSION,
	SYMBOL,
	SYSTEMOFUNITS,
	UNITOFMEASURECLASS,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__EVENT_DOMAIN,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	__LOAD_TS,
    ROW_NUMBER() OVER (PARTITION BY RECID ORDER BY MODIFIEDDATETIME desc) as RN
    
 FROM {{ ref('src_plax_unitofmeasure') }})
 

SELECT 
   CGKPRDROUNDDOWN,
	DECIMALPRECISION,
	EXPORTTOESKER,
	MODIFIEDDATETIME,
	PALLETTYPE,
	PARTITION,
	RECID,
	RECVERSION,
	SYMBOL,
	SYSTEMOFUNITS,
	UNITOFMEASURECLASS,
	__PK1,
	__SYS_CHANGE_OPERATION,
	__SYS_CHANGE_VERSION,
	__EVENT_DOMAIN,
	__EVENT_ID,
	__EVENT_SOURCE,
	__EVENT_TS,
	__EVENT_TYPE,
	__LOAD_TS
from CTE 
WHERE RN=1 and __SYS_CHANGE_OPERATION<>'D'

